name: Save Encoded Payload

on: 
  repository_dispatch:
    types: [payload_received]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Wrap Payload
        run: |
          # 原始负载->包装处理
          echo '${{ toJSON(github.event.client_payload) }}' > raw.json
          python .github/scripts/wrap_payload.py < raw.json > wrapped.json
          
          # 提取包装后内容
          CONTENT=$(cat wrapped.json)
          
      - name: Save File
        run: |
          FILENAME="payload-$(date -u +'%s').txt"
          echo "$CONTENT" > $FILENAME
          gzip -c $FILENAME > ${FILENAME}.gz  # 压缩存储可选

      - name: Commit Changes
        run: |
          git config user.name "auto-saver"
          git config user.email "save@github"
          git add *.txt *.gz
          git commit -m "Saved payload $FILENAME"
          git push


      # 可选：添加执行结果通知
      - name: Notification
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.action === 'payload_received') {
              console.log(`✅ Success! Payload saved at commit ${context.sha}`);
            }
